package aigt.finaccounts.common.models.stubcase

enum class ContextStubCase {
    NONE,
    SUCCESS,
    NOT_FOUND,
    BAD_ID,
    BAD_DESCRIPTION,
    BAD_OWNER_ID,
    BAD_BALANCE,
    BAD_CURRENCY,
    BAD_LAST_TRANSACTION,
    BAD_STATUS,
    BAD_TRANSACTION_AMOUNT,
    BAD_TRANSACTION_COUNTERPARTY,
    BAD_TRANSACTION_TIMESTAMP,
    BAD_TRANSACTION_DESCRIPTION,
    BAD_TRANSACTION_TYPE,
    BAD_SEARCH_STRING,
    DB_ERROR,
}
